### PR TITLE
Add support for US english date format

### PR DESCRIPTION
**Pull request by IngoMeyer441**

### CODE REVIEW

**Comment by m42e** [comment]
@IngoMeyer441 nice, would you mind adding a flag to override it? I prefer en_us setting but still are more familiar with the German date format.

**Comment by IngoMeyer441** [comment]
No, problem, do you have any preferences for the flag (for example environment variable or [zstyle](https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#The-zsh_002fzutil-Module) setting)?

**Comment by m42e** [comment]
as currently `zstyle` is not used within the script I would stick with a simple environment variable.

**Comment by IngoMeyer441** [comment]
👍 Keep things simple

**Comment by IngoMeyer441** [comment]
`FZF_HISTDB_FORCE_DATE_FORMAT` is added in the second commit.

**Comment by m42e** [comment]
Thanks a lot!

**Pull request merged**
